Implementing bitcode.
aboutcode-org/bitcode pull request #1
Opened 2023-06-28 05:04 UTC by 35C4n0r

This PR Implements the pure python variant of intbitset.

Class:
- [ ] intbitset

Methods:
- [ ] add
- [ ] clear
- [ ] copy
- [ ] difference
- [ ] difference_update
- [ ] discard
- [ ] extract_finite_list
- [ ] fastdump
- [ ] fastload
- [ ] get_allocated
- [ ] get_size
- [ ] get_wordbitsize
- [ ] get_wordbytesize
- [ ] intersection
- [ ] intersection_update
- [ ] isdisjoint
- [ ] issubset
- [ ] issuprset
- [ ] is_infinite
- [ ] pop
- [ ] remove
- [ ] strbits
- [ ] symetric_difference
- [ ] symetric_difference_update
- [ ] tolist
- [ ] union
- [ ] union_update
- [ ] update
- [ ] update_with_signs

2023-07-01 01:08 UTC, JonoYang requested changes
@35C4n0r Just pointing out a few small things

2023-07-01 01:08 UTC, JonoYang commented on src/bitcode/intbitset.py
> +# ahocode is a trademark of nexB Inc.
```suggestion
# bitcode is a trademark of nexB Inc.

```

2023-07-01 01:08 UTC, JonoYang commented on src/bitcode/intbitset.py
> +# See https://github.com/nexB/ahocode for support or download.
```suggestion
# See https://github.com/nexB/bitcode for support or download.

```

2023-07-01 01:08 UTC, JonoYang commented on src/bitcode/intbitset.py
> +        intbitset.bitset = self.bitset
Should this be `new.bitset = self.bitset`?

2023-07-01 14:21 UTC, 35C4n0r commented
@JonoYang, thanks for the review. I have added the changes, a few tests, and I also tried adding the github workflow to run the test.

2023-07-03 20:03 UTC, JonoYang commented
@35C4n0r I've enabled Azure Pipelines for CI testing on the ahocode and bitcode repos

2023-07-09 17:56 UTC, 35C4n0r commented
@JonoYang I have removed the github workflows.

2023-07-09 17:57 UTC, 35C4n0r commented
@JonoYang also please make a repo for lxml so that I can start working on it.

2023-07-11 00:01 UTC, JonoYang commented
@35C4n0r I've created the xml fallback library repo at https://github.com/nexb/sanexml

2023-07-13 16:57 UTC, JonoYang commented
@35C4n0r Is there anything else you need to add to this PR, otherwise I will merge it.

2023-07-14 18:24 UTC, 35C4n0r commented
@JonoYang, I don't have anything more to add to PR.

2023-07-14 21:32 UTC, JonoYang commented
@35C4n0r I will merge the PR. Thanks for the contributions!

2023-07-14 21:33 UTC, merged